const backend = {
  baseUrl: '/backend',
  detector: {
    classes: [{
      name: 'human',
      label: 'real human photo'
    },{
      name: 'human_gen',
      label: 'human face generated by AI'
    },{
      name: 'anime',
      label: 'cartoon face drawn by artist'
    },{
      name: 'anime_gen',
      label: 'cartoon face generated by AI'
    }],
    models: [{
      name: 'ensemble_stacking224',
      label: 'Stacked Ensemble',
      accept: ['.h5']
    },{
      name: 'experiment',
      label: 'Experiment',
      accept: ['.h5']
    },{
      name: 'resnet50v2',
      label: 'ResNet50 v2',
      accept: ['.h5']
    },{
      name: 'resnet101v2',
      label: 'ResNet101 v2',
      accept: ['.h5']
    },{
      name: 'resnet152v2',
      label: 'ResNet152 v2',
      accept: ['.h5']
    },{
      name: 'vgg16',
      label: 'VGG16',
      accept: ['.h5']
    },{
      name: 'vgg19',
      label: 'VGG19',
      accept: ['.h5']
    },{
      name: 'mobilenet_v2',
      label: 'MobileNet v2',
      accept: ['.h5']
    },{
      name: 'nasnet_mobile',
      label: 'NASNet Mobile',
      accept: ['.h5']
    },{
      name: 'nasnet_large',
      label: 'NASNet Large',
      accept: ['.h5']
    },{
      name: 'densenet121',
      label: 'DenseNet121',
      accept: ['.h5']
    },{
      name: 'densenet169',
      label: 'DenseNet169',
      accept: ['.h5']
    },{
      name: 'densenet201',
      label: 'DenseNet201',
      accept: ['.h5']
    },{
      name: 'inception_v3',
      label: 'Inception v3',
      accept: ['.h5']
    },{
      name: 'inception_resnet_v2',
      label: 'Inception ResNet v2',
      accept: ['.h5']
    },{
      name: 'xception',
      label: 'Xception',
      accept: ['.h5']
    }]
  },
  generator: {
    models: [{
      name: 'stylegan2',
      label: 'StyleGAN2',
      accept: ['.pkl'],
      backend: 'tf1'
    }],
    batchSize: 10
  }
};

function getModel({name}){
  return [
    ...backend.generator.models,
    ...backend.detector.models
  ].filter(m => m.name === name)[0];
}

export {backend, getModel};
export default {backend, getModel};