const backend = {
  baseUrl: '/backend',
  detector: {
    classes: [{
      name: 'human',
      label: 'real human photo'
    },{
      name: 'human_gen',
      label: 'human face generated by AI'
    },{
      name: 'anime',
      label: 'cartoon face drawn by artist'
    },{
      name: 'anime_gen',
      label: 'cartoon face generated by AI'
    }],
    models: [{
      name: 'experiment',
      label: 'Experiment',
      accept: ['.h5']
    },{
      name: 'resnet50v2',
      label: 'ResNet50 v2',
      accept: ['.h5']
    }]
  },
  generator: {
    models: [{
      name: 'stylegan2',
      label: 'StyleGAN2',
      accept: ['.pkl'],
      backend: 'tf1'
    }],
    batchSize: 10
  }
};

function getModel({name}){
  return [
    ...backend.generator.models,
    ...backend.detector.models
  ].filter(m => m.name === name)[0];
}

export {backend, getModel};
export default {backend, getModel};