version: '3'

volumes:
  entities:
    external: false
    
services:
  frontend:
    image: "vlab-frontend:dev"
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: "vlab-backend-base:dev"
    environment:
      DB_HOST: database
    ports:
      - "5100:5000"
    depends_on:
      - database
  database:
    image: "mysql:5.7.26"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: vlab
    ports:
      - "3306:3306"
    volumes:
      - entities:/var/lib/mysql